# Generated by Django 3.1.2 on 2020-12-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='icon2.jpg', null=True, upload_to='profileImg'),
        ),
    ]
