# Generated by Django 3.1.2 on 2020-11-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instantOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('date', models.DateField()),
                ('Time', models.TimeField()),
                ('loadDesc', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
