# Generated by Django 3.1.2 on 2020-11-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantorders',
            name='n_labours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instantorders',
            name='truck',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
