# Generated by Django 3.1.2 on 2020-11-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201123_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantorders',
            name='phone',
            field=models.PositiveBigIntegerField(max_length=11),
        ),
    ]
