# Generated by Django 3.1.2 on 2020-12-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_memberorders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberorders',
            old_name='username',
            new_name='memberId',
        ),
    ]
