# Generated by Django 3.1.2 on 2020-12-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20201212_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberorders',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='memberorders',
            name='time',
            field=models.TextField(),
        ),
    ]
