# Generated by Django 3.1.2 on 2020-12-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201212_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberorders',
            name='phone',
            field=models.TextField(),
        ),
    ]
