# Generated by Django 3.1.2 on 2020-12-12 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_auto_20201212_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='memberOrders',
            new_name='memberOrdersmodel',
        ),
    ]
