# Generated by Django 3.1.2 on 2020-12-13 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0014_auto_20201213_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberordersmodel',
            name='memberId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
