# Generated by Django 3.1.2 on 2020-12-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20201213_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberordersmodel',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='memberordersmodel',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='memberordersmodel',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
