# Generated by Django 3.1.2 on 2020-12-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20201213_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberordersmodel',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
