# Generated by Django 3.1.2 on 2020-12-13 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20201213_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instantorders',
            old_name='location',
            new_name='load_location',
        ),
        migrations.RenameField(
            model_name='memberordersmodel',
            old_name='location',
            new_name='load_location',
        ),
        migrations.AddField(
            model_name='instantorders',
            name='unload_location',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberordersmodel',
            name='unload_location',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
