# Generated by Django 3.1.2 on 2021-01-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
