# Generated by Django 3.1.2 on 2021-01-02 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantorders',
            name='status',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='orders.category'),
        ),
        migrations.AddField(
            model_name='memberordersmodel',
            name='status',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='orders.category'),
        ),
    ]
