# Generated by Django 3.1.2 on 2021-01-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20210102_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instantorders',
            name='status',
        ),
        migrations.RemoveField(
            model_name='memberordersmodel',
            name='status',
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
